# Product Service - Service Definition
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: production
  labels:
    app: product-service
    environment: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /api/v1/health
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  clusterIP: 172.20.44.190  # Optional: specify if you want a fixed IP
  selector:
    app: product-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None
  publishNotReadyAddresses: false