apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: production
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service-sa
      containers:
      - name: order-service
        image: 928475935003.dkr.ecr.ap-northeast-2.amazonaws.com/order-service:v2
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_REGION
        - name: DYNAMODB_TABLE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DYNAMODB_ORDERS_TABLE
        - name: KAFKA_BROKERS
          value: kafka-service.production.svc.cluster.local:9092
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
      - key: node-role
        operator: Equal
        value: app
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30612
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::928475935003:role/EKSOrderServiceRole
