apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: production
spec:
  template:
    spec:
      containers:
      - name: spiffe-helper
        image: ghcr.io/spiffe/spiffe-helper:latest
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: spire-certs
          mountPath: /run/spire/certs
        - name: spiffe-helper-config
          mountPath: /etc/spiffe-helper
        command: ["/opt/spiffe-helper/spiffe-helper"]
        args: ["-config", "/etc/spiffe-helper/helper.conf"]
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
      - name: spire-certs
        emptyDir: {}
      - name: spiffe-helper-config
        configMap:
          name: spiffe-helper-config