# Namespaces configuration
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: prod
    team: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: prod
    team: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: prod
    team: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    environment: prod
    team: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    name: karpenter
    environment: prod
    team: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: scale-test
  labels:
    name: scale-test
    environment: test
    team: platform